/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dist_lr_CONSTANTS_H
#define dist_lr_CONSTANTS_H

#include "dist_lr_types.h"



class dist_lrConstants {
 public:
  dist_lrConstants();

};

extern const dist_lrConstants g_dist_lr_constants;



#endif
