/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dist_lr_constants.h"



const dist_lrConstants g_dist_lr_constants;

dist_lrConstants::dist_lrConstants() {
}



